### ISSUE TITLE
Locally building application

### ISSUE THREAD

**Issue by maniax89** [react-querybuilder/react-querybuilder#3]
I'm trying to get this up and running in my local environment but have been unable to do so. Here's my step-by-step with debugging:

```
➜  react-querybuilder git:(master) npm --version
3.8.9
➜  react-querybuilder git:(master) npm install
npm WARN deprecated babel-preset-es2015-webpack@6.4.3: Use preset options to disable module transformation https://github.com/gajus/babel-preset-es2015-webpack#deprecated
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

...

react-querybuilder@1.1.0
...ommitted install tree...

npm WARN react-querybuilder@1.1.0 requires a peer of react@^15.2.1 but none was installed.
npm WARN react-querybuilder@1.1.0 requires a peer of react-dom@^15.2.1 but none was installed.
npm WARN react-addons-test-utils@15.3.2 requires a peer of react@^15.3.2 but none was installed.
npm WARN enzyme@2.4.1 requires a peer of react@0.13.x || 0.14.x || ^15.0.0-0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
➜  react-querybuilder git:(master) npm start

> react-querybuilder@1.1.0 start /Users/user/Dev/react-querybuilder
> webpack-dev-server --env dev


/Users/user/Dev/react-querybuilder/node_modules/webpack/lib/webpack.js:16
        throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
        ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].resolve.extensions[0] should not be empty.
 - configuration[1].output.library should be one of these:
   string | [string]
   If set, export the bundle as library. `output.library` is the name.
 - configuration[1].resolve.extensions[0] should not be empty.
    at webpack (/Users/user/Dev/react-querybuilder/node_modules/webpack/lib/webpack.js:16:9)
    at processOptions (/Users/user/Dev/react-querybuilder/node_modules/webpack-dev-server/bin/webpack-dev-server.js:269:17)
    at Object.<anonymous> (/Users/user/Dev/react-querybuilder/node_modules/webpack-dev-server/bin/webpack-dev-server.js:297:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! react-querybuilder@1.1.0 start: `webpack-dev-server --env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-querybuilder@1.1.0 start script 'webpack-dev-server --env dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-querybuilder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-querybuilder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-querybuilder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Dev/react-querybuilder/npm-debug.log
```

So I proceed by trying to comment out just the lines in `webpack.config.js` to read:

```
'use strict';

module.exports = env=> {
    return [
        require('./config/webpack-dev.config'),
        //require('./config/webpack-prod.config')
    ];
};
```

Also modified the `config/webpack-common.config.js` to remove the empty '' element:

```
...
resolve: {
        extensions: ['.js', '.jsx', '.scss']
    },
...
```

Running `npm start` again, I get a new error:

```
➜  react-querybuilder git:(master) npm start

> react-querybuilder@1.1.0 start /Users/user/Dev/react-querybuilder
> webpack-dev-server --env dev

 http://localhost:8080/
webpack result is served from /
content is served from /Users/user/Dev/react-querybuilder
404s will fallback to /index.html
/Users/user/Dev/react-querybuilder/node_modules/webpack/lib/Chunk.js:34
    throw new Error("Chunk.entry was removed. Use hasRuntime()");
    ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.Object.defineProperty.get (/Users/user/Dev/react-querybuilder/node_modules/webpack/lib/Chunk.js:34:9)
    at /Users/user/Dev/react-querybuilder/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/Users/user/Dev/react-querybuilder/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins (/Users/user/Dev/react-querybuilder/node_modules/tapable/lib/Tapable.js:25:14)
    at Compilation.seal (/Users/user/Dev/react-querybuilder/node_modules/webpack/lib/Compilation.js:542:7)
    at Compiler.<anonymous> (/Users/user/Dev/react-querybuilder/node_modules/webpack/lib/Compiler.js:468:16)
```

Reading online, seems there is a problem with the extract-text-webpack-plugin, see https://github.com/webpack/webpack/issues/2764 so I tried the suggestion of using the versions of webpack and extract-text-webpack-plugin but yet another new error appears:

```
➜  react-querybuilder git:(master) ✗ npm install
react-querybuilder@1.1.0 /Users/user/Dev/react-querybuilder
├── extract-text-webpack-plugin@2.0.0-beta.4
├── UNMET PEER DEPENDENCY react@^15.2.1
├── UNMET PEER DEPENDENCY react-dom@^15.2.1
└─┬ webpack@2.1.0-beta.25
  ├── acorn@3.3.0
  ├── supports-color@3.1.2
  ├─┬ uglify-js@2.7.3
  │ ├── async@0.2.10
  │ └─┬ yargs@3.10.0
  │   └── camelcase@1.2.1
  └─┬ yargs@4.8.1
    ├── cliui@3.2.0
    └── window-size@0.2.0

npm WARN react-querybuilder@1.1.0 requires a peer of react@^15.2.1 but none was installed.
npm WARN react-querybuilder@1.1.0 requires a peer of react-dom@^15.2.1 but none was installed.
npm WARN enzyme@2.4.1 requires a peer of react@0.13.x || 0.14.x || ^15.0.0-0 but none was installed.
npm WARN react-addons-test-utils@15.3.2 requires a peer of react@^15.3.2 but none was installed.
➜  react-querybuilder git:(master) ✗ npm start

> react-querybuilder@1.1.0 start /Users/user/Dev/react-querybuilder
> webpack-dev-server --env dev

 http://localhost:8080/
webpack result is served from /
content is served from /Users/user/Dev/react-querybuilder
404s will fallback to /index.html
Child
    chunk    {0} demo.bundle.js, demo.bundle.js.map (demo) 233 kB [entry] [rendered]

    ERROR in ./demo/main.js
    Module build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.
        at Object.<anonymous> (/Users/user/Dev/react-querybuilder/node_modules/babel-preset-es2015-webpack/index.js:35:11)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:456:32)
        at tryModuleLoad (module.js:415:12)
        at Function.Module._load (module.js:407:3)
        at Module.require (module.js:466:17)
        at require (internal/module.js:20:19)
        at /Users/user/Dev/react-querybuilder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:284:15
        at Array.map (native)
        at OptionManager.resolvePresets (/Users/user/Dev/react-querybuilder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
        at OptionManager.mergePresets (/Users/user/Dev/react-querybuilder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:254:10)
        at OptionManager.mergeOptions (/Users/user/Dev/react-querybuilder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:239:14)
        at OptionManager.init (/Users/user/Dev/react-querybuilder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
        at File.initOptions (/Users/user/Dev/react-querybuilder/node_modules/babel-core/lib/transformation/file/index.js:216:65)
        at new File (/Users/user/Dev/react-querybuilder/node_modules/babel-core/lib/transformation/file/index.js:137:24)
     @ multi demo
    Child html-webpack-plugin for "index.html":
        chunk    {0} index.html 536 kB [entry] [rendered]
webpack: bundle is now VALID.
```

I was unable to find a solution to this. Is there something I am missing in order to be able to run this locally? Would help in order for me to start making a PR. Thanks.

**Comment by maniax89** [comment]
I was able to figure out the `Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list` by changing the `.babelrc` file to read like:

```
"presets": [
        "es2015",
        "react"
    ],
```

After installing the peerDependencies manually (`react` and `react-dom`) I was able to get this up and running locally.
