### ISSUE TITLE
parameterized_named is giving error

### ISSUE THREAD

**Issue by AkshaySeth94** [react-querybuilder/react-querybuilder#568]
Below is my code:

```tsx
import { QueryBuilderAntD } from '@react-querybuilder/antd';
import { useState } from 'react';
import { QueryBuilder, formatQuery } from 'react-querybuilder';
import './App.css';

const fields = [
  { name: 'firstName', label: 'First Name', inputType: 'date' },
  { name: 'lastName', label: 'Last Name' },
];

const initialQuery = {
  combinator: 'and',
  rules: [
    { field: 'firstName', operator: 'beginsWith', value: '' },
    { field: 'lastName', operator: 'in', value: '' },
  ],
};

const App = () => {
  const [query, setQuery] = useState(initialQuery);

  return (
    <div>
      <br></br>
      <QueryBuilderAntD>
        <QueryBuilder
          fields={fields}
          query={query}
          onQueryChange={q => setQuery(q)}
        />
      </QueryBuilderAntD>
      <h4>Query</h4>
      <pre>
        <code>{formatQuery(query, 'parameterized_named')}</code>
      </pre>
    </div>
  );
};
export default App;
```

When I am passing "sql" or "json" in formatQuery function everything is working as expected but when I pass parameterized_named in this function everything is failing and I am getting below error on my webpage:

```
Uncaught runtime errors:
×
ERROR
Objects are not valid as a React child (found: object with keys {sql, params}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:3000/static/js/bundle.js:61892:13)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:62668:11)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:65595:32)
    at updateHostComponent (http://localhost:3000/static/js/bundle.js:66239:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:67684:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:52670:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:52714:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:52771:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:72645:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:71892:16)

```

**Comment by jakeboone02** [comment]
When you use the `"parameterized"` or `"parameterized_named"` formats, the output of `formatQuery` is not a `string` but an object (which is why you get the "Objects are not valid as a React child" error). The easiest way to display a plain object in React is to `JSON.stringify()` it. I would recommend indenting as well:

```diff
       <pre>
-        <code>{formatQuery(query, 'parameterized_named')}</code>
+        <code>{JSON.stringify(formatQuery(query, 'parameterized_named'), null, 2)}</code>
       </pre>
```
